[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
jukebox_contract = "9V7dPoV7FHTawjh1ct3PprRPEGGAePHGRgWPUQ3VSu8k"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/ahmtguler/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
